Resources:
  CandidateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.candidateTable}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: emailAddress
          AttributeType: S
      KeySchema:
        - AttributeName: emailAddress
          KeyType: HASH
        # - ProvisionedThroughput:
        #   ReadCapacityUnits: 1
        #   WriteCapacityUnits: 1

# Set the billing mode to Pay as you use
#    BillingMode: PAY_PER_REQUEST